# Generate secret keys using the moving-averaged CSI data 
# method. For this, apply 
# quantization to the moving-averaged CSI datasets for 
# both the AP and STA. For example, you may use the 
# dataset-wide average CSI as a threshold: values above 
# the threshold are mapped to +1, and values below it are 
# mapped to 1. Assume that each key has a length of 128 
# bits, and split the generated bitstream into a sequence 
# of 128-bit keys. For each pair of keys generated by the 
# AP and STA, determine whether they are in agreement based 
# on a predefined error threshold of 10%. Specifically, 
# if the fraction of mismatched bits between the two keys 
# is less than 10%, classify the pair as a key 
# generation success; otherwise, classify it as a failure. 
# Perform this agreement check for all generated key pairs, 
# and compute the average key generation rate (KGR), 
# defined as the fraction of successfully generated keys 
# over the total number of keys. 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

KEY_LENGTH = 128
ERROR_THRESHOLD = 0.1
SAMPLE_COUNT = 20000
SUBCARRIER_COUNT = 64

# Load CSI data
apData = pd.read_csv('ap.csv', header=None).values.astype(float)
staData = pd.read_csv('sta.csv', header=None).values.astype(float)